service: service

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}
  timeout: 20
  memorySize: 128 # MB
  environment:
    BUCKET_NAME:
      Fn::ImportValue: NiceBucketName

functions:
  upload-buffer:
    handler: src/lambdas/upload-buffer.handler
    events:
      - http:
          path: /upload-buffer
          method: get
  upload-stream:
    handler: src/lambdas/upload-stream.handler
    events:
      - http:
          path: /upload-stream
          method: get
  multi-upload:
    handler: src/lambdas/multi-upload.handler
    events:
      - http:
          path: /multi-upload
          method: get

custom:
  esbuild:
    bundle: true
    minify: true

plugins:
  - serverless-offline
  - serverless-esbuild
