version: '3.8'

services:
  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    user: root
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      AWS_REGION: us-west-1
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

volumes:
  dynamodb_data:
